events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type "text/html";
    
    server {
        listen 80;

        rewrite ^/(.*)/$ /$1 permanent;


        location / {
            root /app;
        
            try_files  $uri $uri.html $uri/index.html index.html;

            error_page 404 /404.html;
        }
    }
}
