name: Lint and Formatting Checks

on:
  pull_request:
    branches:
      - main

jobs:       
  lint:
    name: Server linting and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Prettier Checks
        run: npm run format:check

      - name: ESLint Checks
        run: npm run lint:check